2022-01-18 00:32:34,926 INFO    MainThread:27580 [wandb_setup.py:_flush():71] setting env: {'api_key': '***REDACTED***'}
2022-01-18 00:32:34,927 INFO    MainThread:27580 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-18 00:32:34,927 INFO    MainThread:27580 [wandb_init.py:_log_setup():371] Logging user logs to c:\Users\rufai\Downloads\assignment-instructions\assignment\wandb\run-20220118_003234-26snzq9h\logs\debug.log
2022-01-18 00:32:34,927 INFO    MainThread:27580 [wandb_init.py:_log_setup():372] Logging internal logs to c:\Users\rufai\Downloads\assignment-instructions\assignment\wandb\run-20220118_003234-26snzq9h\logs\debug-internal.log
2022-01-18 00:32:34,927 INFO    MainThread:27580 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000016C0F408A90>
2022-01-18 00:32:34,928 INFO    MainThread:27580 [wandb_init.py:init():404] calling init triggers
2022-01-18 00:32:34,928 INFO    MainThread:27580 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-18 00:32:34,928 INFO    MainThread:27580 [wandb_init.py:init():460] starting backend
2022-01-18 00:32:34,928 INFO    MainThread:27580 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-01-18 00:32:34,932 INFO    MainThread:27580 [backend.py:ensure_launched():216] starting backend process...
2022-01-18 00:32:35,078 INFO    MainThread:27580 [backend.py:ensure_launched():221] started backend process with pid: 15456
2022-01-18 00:32:35,079 INFO    MainThread:27580 [wandb_init.py:init():469] backend started and connected
2022-01-18 00:32:35,095 INFO    MainThread:27580 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-18 00:32:35,095 INFO    MainThread:27580 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-18 00:32:35,095 INFO    MainThread:27580 [wandb_init.py:init():533] updated telemetry
2022-01-18 00:32:35,099 INFO    MainThread:27580 [wandb_init.py:init():563] communicating current version
2022-01-18 00:32:37,492 INFO    MainThread:27580 [wandb_init.py:init():568] got version response 
2022-01-18 00:32:37,492 INFO    MainThread:27580 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-18 00:32:37,754 INFO    MainThread:27580 [wandb_init.py:init():606] starting run threads in backend
2022-01-18 00:32:42,771 INFO    MainThread:27580 [wandb_run.py:_console_start():1810] atexit reg
2022-01-18 00:32:42,772 INFO    MainThread:27580 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-18 00:32:42,772 INFO    MainThread:27580 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-18 00:32:42,773 INFO    MainThread:27580 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-18 00:32:42,774 INFO    MainThread:27580 [wandb_init.py:init():633] run started, returning control to user process
2022-01-18 00:32:42,816 INFO    MainThread:27580 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-18 00:32:42,816 INFO    MainThread:27580 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-18 00:33:22,833 INFO    MainThread:27580 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-18 00:33:22,846 INFO    MainThread:27580 [wandb_setup.py:_flush():71] setting env: {'api_key': '***REDACTED***'}
2022-01-18 00:33:22,846 INFO    MainThread:27580 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-18 00:33:22,847 INFO    MainThread:27580 [wandb_init.py:_log_setup():371] Logging user logs to c:\Users\rufai\Downloads\assignment-instructions\assignment\wandb\run-20220118_003322-2cdwn8en\logs\debug.log
2022-01-18 00:33:22,847 INFO    MainThread:27580 [wandb_init.py:_log_setup():372] Logging internal logs to c:\Users\rufai\Downloads\assignment-instructions\assignment\wandb\run-20220118_003322-2cdwn8en\logs\debug-internal.log
2022-01-18 00:33:22,847 INFO    MainThread:27580 [wandb_init.py:init():404] calling init triggers
2022-01-18 00:33:22,847 INFO    MainThread:27580 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-18 00:33:22,847 INFO    MainThread:27580 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 26snzq9h
2022-01-18 00:33:22,849 INFO    MainThread:27580 [wandb_run.py:finish():1457] finishing run ruphai/Oil Palm Classification/26snzq9h
2022-01-18 00:33:22,849 INFO    MainThread:27580 [jupyter.py:save_history():429] not saving jupyter history
2022-01-18 00:33:22,850 INFO    MainThread:27580 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-18 00:33:22,850 INFO    MainThread:27580 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-18 00:33:22,850 INFO    MainThread:27580 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-18 00:33:22,851 INFO    MainThread:27580 [wandb_run.py:_restore():1752] restore
2022-01-18 00:33:23,455 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 882
}

2022-01-18 00:33:23,579 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 882
}

2022-01-18 00:33:23,866 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 882
}

2022-01-18 00:33:24,193 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 24194
}

2022-01-18 00:33:24,304 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 24221
}

2022-01-18 00:33:24,413 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 24221
}

2022-01-18 00:33:24,536 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 00:33:24,647 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 00:33:24,754 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 00:33:24,862 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 00:33:24,971 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 00:33:25,532 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 00:33:26,056 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}
local_info {
}

2022-01-18 00:33:27,681 INFO    MainThread:27580 [wandb_run.py:_append_files():2180] logging synced files
