
Epoch 0:   2%|▏         | 2/85 [00:00<00:27,  3.04it/s, loss=1.59, v_num=u3bj, Train_loss_step=1.650]
wandb: WARNING Serializing object of type DataFrame that is 929061 bytes
  | Name              | Type     | Params
-----------------------------------------------
0 | feature_extractor | ResNet   | 11.7 M
1 | classifier        | Linear   | 2.0 K
2 | train_accuracy    | Accuracy | 0
3 | train_f1          | F1       | 0
4 | val_accuracy      | Accuracy | 0
5 | val_f1            | F1       | 0
6 | val_fbeta         | FBeta    | 0
7 | test_accuracy     | Accuracy | 0
8 | test_f1           | F1       | 0
9 | test_fbeta        | FBeta    | 0
-----------------------------------------------
2.0 K     Trainable params
11.7 M    Non-trainable params
11.7 M    Total params
23.383    Total estimated model params size (MB)
C:\Users\rufai\anaconda3\lib\site-packages\pytorch_lightning\trainer\data_loading.py:132: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\rufai\anaconda3\lib\site-packages\pytorch_lightning\trainer\data_loading.py:132: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.







Epoch 0:  72%|███████▏  | 61/85 [00:16<00:06,  3.70it/s, loss=0.365, v_num=u3bj, Train_loss_step=0.333]











Epoch 1:  74%|███████▍  | 63/85 [00:16<00:05,  3.71it/s, loss=0.262, v_num=u3bj, Train_loss_step=0.247, Val_loss=0.303, Acc_val=0.885, Train_loss_epoch=0.669]


Validating:  77%|███████▋  | 20/26 [00:05<00:01,  3.88it/s]








Epoch 2:  71%|███████   | 60/85 [00:16<00:06,  3.71it/s, loss=0.256, v_num=u3bj, Train_loss_step=0.183, Val_loss=0.266, Acc_val=0.908, Train_loss_epoch=0.271]


Validating:  65%|██████▌   | 17/26 [00:04<00:02,  3.74it/s]








Epoch 3:  71%|███████   | 60/85 [00:15<00:06,  3.83it/s, loss=0.244, v_num=u3bj, Train_loss_step=0.338, Val_loss=0.259, Acc_val=0.907, Train_loss_epoch=0.252]











Epoch 4:  71%|███████   | 60/85 [00:15<00:06,  3.91it/s, loss=0.234, v_num=u3bj, Train_loss_step=0.216, Val_loss=0.251, Acc_val=0.912, Train_loss_epoch=0.235]


Validating:  69%|██████▉   | 18/26 [00:04<00:02,  3.90it/s]








Epoch 5:  71%|███████   | 60/85 [00:15<00:06,  3.82it/s, loss=0.213, v_num=u3bj, Train_loss_step=0.117, Val_loss=0.248, Acc_val=0.911, Train_loss_epoch=0.231]




Epoch 5, global step 353: Val_loss reached 0.25067 (best 0.24750), saving model to "C:\Users\rufai\Downloads\assignment-instructions\assignment\best-model\OilPalmRes\./best-model/OilPalmRes/-epoch=05--val_loss=0.00.ckpt" as top 5
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
wandb: WARNING Serializing object of type DataFrame that is 929061 bytes
C:\Users\rufai\anaconda3\lib\site-packages\pytorch_lightning\trainer\data_loading.py:132: UserWarning: The dataloader, test_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(




Testing:  97%|█████████▋| 35/36 [00:10<00:00,  3.32it/s]\Test Accuracy: 0.0000, F1 Score: 0.0000FBeta Score: 0.0000
--------------------------------------------------------------------------------
DATALOADER:0 TEST RESULTS
{'Acc_test': 0.9296875,
 'Test_F1': 0.8317074179649353,
 'Test_FBeta': 0.8317074179649353}
--------------------------------------------------------------------------------
Testing: 100%|██████████| 36/36 [00:10<00:00,  3.44it/s]
C:\Users\rufai\anaconda3\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric Accuracy was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)
C:\Users\rufai\anaconda3\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric F1 was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)
C:\Users\rufai\anaconda3\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric FBeta was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)