2022-01-18 01:17:34,942 INFO    MainThread:27580 [wandb_setup.py:_flush():71] setting env: {'api_key': '***REDACTED***'}
2022-01-18 01:17:34,942 INFO    MainThread:27580 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-18 01:17:34,942 INFO    MainThread:27580 [wandb_init.py:_log_setup():371] Logging user logs to c:\Users\rufai\Downloads\assignment-instructions\assignment\wandb\run-20220118_011734-26v9x9qm\logs\debug.log
2022-01-18 01:17:34,943 INFO    MainThread:27580 [wandb_init.py:_log_setup():372] Logging internal logs to c:\Users\rufai\Downloads\assignment-instructions\assignment\wandb\run-20220118_011734-26v9x9qm\logs\debug-internal.log
2022-01-18 01:17:34,943 INFO    MainThread:27580 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000016C1F38B490>
2022-01-18 01:17:34,943 INFO    MainThread:27580 [wandb_init.py:init():404] calling init triggers
2022-01-18 01:17:34,944 INFO    MainThread:27580 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-18 01:17:34,944 INFO    MainThread:27580 [wandb_init.py:init():460] starting backend
2022-01-18 01:17:34,944 INFO    MainThread:27580 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-01-18 01:17:34,947 INFO    MainThread:27580 [backend.py:ensure_launched():216] starting backend process...
2022-01-18 01:17:35,072 INFO    MainThread:27580 [backend.py:ensure_launched():221] started backend process with pid: 17072
2022-01-18 01:17:35,073 INFO    MainThread:27580 [wandb_init.py:init():469] backend started and connected
2022-01-18 01:17:35,075 INFO    MainThread:27580 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-18 01:17:35,075 INFO    MainThread:27580 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-18 01:17:35,075 INFO    MainThread:27580 [wandb_init.py:init():533] updated telemetry
2022-01-18 01:17:35,075 INFO    MainThread:27580 [wandb_init.py:init():563] communicating current version
2022-01-18 01:17:38,127 INFO    MainThread:27580 [wandb_init.py:init():568] got version response 
2022-01-18 01:17:38,128 INFO    MainThread:27580 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-18 01:17:38,378 INFO    MainThread:27580 [wandb_init.py:init():606] starting run threads in backend
2022-01-18 01:17:43,403 INFO    MainThread:27580 [wandb_run.py:_console_start():1810] atexit reg
2022-01-18 01:17:43,403 INFO    MainThread:27580 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-18 01:17:43,404 INFO    MainThread:27580 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-18 01:17:43,405 INFO    MainThread:27580 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-18 01:17:43,405 INFO    MainThread:27580 [wandb_init.py:init():633] run started, returning control to user process
2022-01-18 01:17:43,423 INFO    MainThread:27580 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-18 01:17:43,423 INFO    MainThread:27580 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-18 01:21:04,155 INFO    MainThread:27580 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-18 01:21:04,156 INFO    MainThread:27580 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-18 01:21:04,157 INFO    MainThread:27580 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-18 01:21:06,337 INFO    MainThread:27580 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-18 01:21:06,354 INFO    MainThread:27580 [wandb_setup.py:_flush():71] setting env: {'api_key': '***REDACTED***'}
2022-01-18 01:21:06,355 INFO    MainThread:27580 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-18 01:21:06,355 INFO    MainThread:27580 [wandb_init.py:_log_setup():371] Logging user logs to c:\Users\rufai\Downloads\assignment-instructions\assignment\wandb\run-20220118_012106-jjqs3wpq\logs\debug.log
2022-01-18 01:21:06,356 INFO    MainThread:27580 [wandb_init.py:_log_setup():372] Logging internal logs to c:\Users\rufai\Downloads\assignment-instructions\assignment\wandb\run-20220118_012106-jjqs3wpq\logs\debug-internal.log
2022-01-18 01:21:06,356 INFO    MainThread:27580 [wandb_init.py:init():404] calling init triggers
2022-01-18 01:21:06,356 INFO    MainThread:27580 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-18 01:21:06,356 INFO    MainThread:27580 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 26v9x9qm
2022-01-18 01:21:06,358 INFO    MainThread:27580 [wandb_run.py:finish():1457] finishing run ruphai/Oil Palm Classification/26v9x9qm
2022-01-18 01:21:06,358 INFO    MainThread:27580 [jupyter.py:save_history():429] not saving jupyter history
2022-01-18 01:21:06,358 INFO    MainThread:27580 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-18 01:21:06,359 INFO    MainThread:27580 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-18 01:21:06,359 INFO    MainThread:27580 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-18 01:21:06,359 INFO    MainThread:27580 [wandb_run.py:_restore():1752] restore
2022-01-18 01:21:06,895 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 882
}

2022-01-18 01:21:07,213 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 882
}

2022-01-18 01:21:08,014 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 24221
}

2022-01-18 01:21:08,120 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 24221
}

2022-01-18 01:21:08,231 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 24221
}

2022-01-18 01:21:08,339 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 882
  total_bytes: 24221
}

2022-01-18 01:21:08,451 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 01:21:08,560 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 01:21:08,670 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 01:21:08,781 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 01:21:08,891 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 01:21:09,432 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}

2022-01-18 01:21:09,942 INFO    MainThread:27580 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 24221
  total_bytes: 24221
}
local_info {
}

2022-01-18 01:21:11,499 INFO    MainThread:27580 [wandb_run.py:_append_files():2180] logging synced files
